### ISSUE TITLE
CalculateExpression

### ISSUE THREAD

**Issue by JLU-WY** [Mythologyli/fxListExporter#1]
请问CalculateExpression可以处理计算表达式吗?类似"2*(23+6)*23-56/6"这样的表达式.复杂的如开方或者指数形式的

**Comment by Mythologyli** [comment]
> 请问CalculateExpression可以处理计算表达式吗?类似"2*(23+6)*23-56/6"这样的表达式.复杂的如开方或者指数形式的

理论上可以运算 RUNMAT 线性模式下的表达式。可以参考 demo 中的方法，拼出要运算的表达式，获得 BCD 编码的结果，再转换为 double。

**Comment by JLU-WY** [comment]
感谢！



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mythologyli/fxListExporter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 下午5:01
收件人:&nbsp;"Mythologyli/fxListExporter"<fxListExporter@noreply.github.com&gt;;
抄送:&nbsp;"Y. Wang"<wyzrp613@jlu.edu.cn&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Mythologyli/fxListExporter] CalculateExpression (#1)





  
请问CalculateExpression可以处理计算表达式吗?类似"2*(23+6)*23-56/6"这样的表达式.复杂的如开方或者指数形式的
  
理论上可以运算 RUNMAT 线性模式下的表达式。可以参考 demo 中的方法，拼出要运算的表达式，获得 BCD 编码的结果，再转换为 double。
